# Generated by Django 3.2 on 2021-04-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTable',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('meeting_type', models.BooleanField()),
                ('max_user', models.IntegerField()),
                ('attendee_name', models.TextField()),
                ('attendee_email', models.TextField()),
                ('chat', models.BooleanField()),
                ('poll', models.BooleanField()),
                ('support_encrypt', models.BooleanField()),
                ('auto_video', models.BooleanField()),
                ('Agenda', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('start_date', models.TextField()),
                ('open_time', models.IntegerField()),
                ('join_teleconf', models.BooleanField()),
                ('enabledAutoRecordMeeting', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('time_zone_id', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
